services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./storage:/app/storage

  redis:
    image: redis:7
    ports:
      - "6379:6379"
